### ISSUE TITLE
Link invite update to upper profile

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#112]
As an upper I want to see who has been invited to the part-up. Now it only shows first names. I want to be able to click the update to go to update detail. And update details should show a list of invitees. When the invitee is an upper, show clickable profile picture or "firstname is not an upper yet" copy (because of privacy no lastname and email).

**Comment by erik-visser** [comment]
When you invite people to be part of a part-up you see a notification in the updates. That great. But if you invite them to an activity it's the same. And then you get: "Erik nodigde Nynke, Joyce, Joyce en Joyce uit voor deze part-up". Maybe you can make this activity specific? That way the groep knows for what activity (which is usefull info) instead of a confusing line.

**Comment by ralphboeije** [comment]
See #78
