### ISSUE TITLE
Delete line break in cookie warning on small screens

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#1238]
Now there is a line break between the button and the text

**Comment by AnnotatedJS** [comment]
I have removed the line break (turns out to be p paragraph tag) and increased margin-right of the button from 0 to 10 px.
See included screenshots for results.
![part up homelarge](https://user-images.githubusercontent.com/11474975/30916922-eddfffce-a39a-11e7-9dc6-1cc645dec7ca.png)
![part up homesmall](https://user-images.githubusercontent.com/11474975/30916941-f774f832-a39a-11e7-9a04-e1382f975227.png)

Let me know if this is what you want and I will push the branch to remote.

**Comment by ralphboeije** [comment]
HI @AnnotatedJS tnx for fixing this issue. A couple of questions:
- Why is the link ("More info") in blue? on production it is white bold
- Can you make it the copy a column, such that the last line is aligned with the other lines (e.g. Part-up serves ...)
- Can you increase top margin on large screen to make the copy appear centered vertically with respect to the button?

**Comment by ralphboeije** [comment]
no improvement, so closed
