### ISSUE TITLE
Language bug

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1502]
I have found that in the `loadData` method in `App.tsx` a subscription to `onLogin` is made.
In the method `componentWillMount` the user get's logged in 3 times already? It's hard to keep track of what's happening with an event driven approach.

the `loadData` is the only method where the locale is set within React so it must be that the handler get's fired the amount of times the user get's logged in to the React part of the app?

How could I test this? I can't reproduce a production environment when testing locally.
I have tried to change some code but TS keeps throwing errors about `any` when I use `this` inside a locally created function.

**Comment by noelheesen** [comment]
I have had the most success in reproducing this bug by:
1. Open 2 different browsers;
2. Login with 1st;
3. Login with 2nd;
4. Language bug appeared in infinite loop

**Comment by andreleon** [comment]
Hi noel, I have tried to reproduce an issue, but I'm not very clear on what the issue is exactly. I can't triger any infinite loops.. Can you describe what the issue is exactly?

**Comment by noelheesen** [comment]
It only happens on a production build. I have recorded a small video to demonstrate: https://drive.google.com/file/d/1udqVY9qSKHdXQyE9CP6H1SNhd7UJfp34/view?usp=sharing

**Comment by ralphboeije** [comment]
Also on staging:  https://drive.google.com/open?id=1Pr2WU0NRigESDrf7BJc1O2egihJm6tFZ

**Comment by andreleon** [comment]
@noelheesen Can you be sure it's because of our changes? I don't see how there is an infinite loop anywhere in the code. If onLogin is triggered multiple times, it is not harmful and this shouldn't (and as far as I can see doesn't) trigger an infinite loop. I do know the blaze templates sometimes rerender a page based om some conditions, so that can cause the underlying react app to re-render.

**Comment by noelheesen** [comment]
It's quite possible that Meteor is doing weird shit and mount the React app multiple times. I don't know how to create a production build so can't test this.

About the multiple logins I was referencing to `App.tsx`

```TSX
// The 'onStartup' will login the user to React

'index.tsx'
window.REACT_USER_LOGIN = () => {
    userDispatcher.dispatch('login', {});
};

'App.tsx'
public componentWillMount() {
  this.loadData(); // This will apply the callback to 'onLogin' and then login once (user should already been logged in from 'onStartup')
  // There's also quite a lot of refetching going on.

  loginWithMeteorToken(); // Login the user to the react app.

  userDispatcher.subscribe('login', this.userLoginHandler); // Listen to login triggered by both 'loadData' and 'index.js' and then login again             /\ wut?.
  userDispatcher.subscribe('logout', this.userLogoutHandler);
}
```

It feels like the user get's logged in multiple times. Even when the `onLogin` callback is being applied only once it get's triggered loads of times. I don't really understand why so many login subs and events are required.

What happens when you remove the `moment.locale()` from the handler? I'd say since we need to have the state in both apps we should use `session` to store it once and retrieve it whenever we need it. This might pose some challenges as it's not reactive by default and a solution needs to be built in React.

**Comment by andreleon** [comment]
@noelheesen 

> About the multiple logins I was referencing to `App.tsx`
> 
> ```TSX
> // The 'onStartup' will login the user to React
> 
> 'index.tsx'
> window.REACT_USER_LOGIN = () => {
>     userDispatcher.dispatch('login', {});
> };
> 
> 'App.tsx'
> public componentWillMount() {
>   this.loadData(); // This will apply the callback to 'onLogin' and then login once (user should already been logged in from 'onStartup')
>   // There's also quite a lot of refetching going on.
> 
>   loginWithMeteorToken(); // Login the user to the react app, just did that in 'loadData'
> 
>   userDispatcher.subscribe('login', this.userLoginHandler); // Listen to login triggered by both 'loadData' and 'index.js' and then login again
>   userDispatcher.subscribe('logout', this.userLogoutHandler);
> }
> ```

> It feels like the user get's logged in multiple times. Even when the `onLogin` callback is being applied only once it get's triggered loads of times.

I get why it feels like that, that's because the `loginWithMeteorToken` is called multiple times on purpose. We cannot be sure the user is logged in in the `onStartup` callback, so we just do it again when we think there might be a `Meteor.loginToken` in localStorage. This should not cause any problems, since our React Meteor instance is smart enough to know when a user is already logged in. But in any case, I have now built in a check within `loginWithMeteorToken` that prevents multiple logins with the same `Meteor.loginToken`. Nice catch.

Also, there is no refetching going on, if you look closer, you can see we only get the user from minimongo (clientside). So no round-trips are happening.

```
private refetchUser = () => {
    this.setState({
        user: Meteor.user(),
    });
}
```
I have renamed this method to `refreshUser` so it's more clear.

> I don't really understand why so many login subs and events are required.

Also, nice catch. I forgot to unsubscribe from the loggedin user in the `componentWillUnmount` hook:
```
public componentWillUnmount() {
    this.currentUserTracker.destroy();

    this.userSubscription.unsubscribe(); // <- here

    userDispatcher.unsubscribe('login', this.userLoginHandler);
    userDispatcher.unsubscribe('logout', this.userLogoutHandler);
}
```

> What happens when you remove the `moment.locale()` from the handler? I'd say since we need to have the state in both apps we should use `session` to store it once and retrieve it whenever we need it. This might pose some challenges as it's not reactive by default and a solution needs to be built in React.

You have to understand that our React app is in an isolated environment, we don't use any of the Meteor/Blaze codebase only in some edge cases (like TAPi18n). So our moment instance is different from the Blaze/Meteor instance. Also, within the `onLogin` callback is the only pace we can be sure we have a valid user object with a language setting. And with the changes I made to `loginWithMeteorToken` it shouldn't be called more than once. And again in this case, calling `moment.locale()` more than once is not harmful.


But to get back to the issue at hand, there is really no way I see this 'infinte loop bug' being related to the react-codebase. As I said, it's completely isolated from the Meteor/Blaze environment, all the way down to the subscriptions being done on collections.

Also, the in the example videos you show, there are no react instances active. Only on the /home page and the partup-start page there are react instances active.

**Comment by andreleon** [comment]
@noelheesen I advise you to record a performance profile while this infinite loop is happening and share it here. That way you can see every call that is being made and maybe narrow the loop down.

<img width="545" alt="screen shot 2018-01-17 at 12 03 32" src="https://user-images.githubusercontent.com/1391492/35039575-8d7684aa-fb7e-11e7-86d6-b6f189a1405d.png">

**Comment by ralphboeije** [comment]
Just discussed this issue with @peterpeerdeman and this is the logical steps:
1. Consistently reproduce and describe steps (steps above by @noelheesen do not lead to consistently reproducible bug by @andreleon)
2. comment out React app and put this branch on staging to double check it is caused by React
3. comment out language subscription on profile (changeLocale) in the meantime?

I will discuss these steps with @noelheesen

**Comment by noelheesen** [comment]
We could also try to comment out setting the locale in `this.getUSerData()` to test if the language bug still appears.

**Comment by noelheesen** [comment]
I'm able to constistently reproduce the bug.

1. Open https://ft-personal-homepage-finish.staging.part-up.com on chrome.
2. Open https://ft-personal-homepage-finish.staging.part-up.com on firefox.
3. Login on chrome and go to the conversations tab of a part-up (in my case dev board).
4. Login on firefox and go to the conversations tab of a part-up (in my case dev board).
5. Refresh firefox.

I also captured the profile with chrome but can't make sense of it.

@ralphboeije could you try these steps and see if you can consistently get the bug as well?
