### ISSUE TITLE
Notification for new tribe member in public tribes is missing

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#158]
To reproduce (logged in in browser 1):
1. Go to a public tribe (e.g. part-up.com/development)
2. Join the tribe if you are not a member yet
3. Open a new browser 2 and log in with a different user account
4. Go to the same tribe
5. Join the tribe
6. Check browser 1 for a notification of a new member in that tribe and see that there is none

**Comment by prik** [comment]
I actually programmed it to not do this on public tribes, since those can get quite loaded with members (look at public Facebook groups). And since you can't disable notifications, I thought it would be unwanted to get a notification for every new upper on a public tribe. 

But I reversed that now, so it works after the next deploy :)
