### ISSUE TITLE
TestCases 1701

### ISSUE THREAD

**Issue by noelheesen** [part-up/part-up#1684]
This issue lists all commits that require testing on acceptance before releasing:

- [x] A deleted activity title now shows with strikethrough;
- [ ] Single update & activity views now have the correct column span;
- [x] Wysiwyg editor on tribe settings / landing page tab now allows to toggle to html source again
- [ ] Enable chat support via profile menu;
- [ ] Fixed floating login button;
- [ ] After accepting a tribe invite the go-to-tribe button changes;
- [ ] Update will still render if a user is deactivated/deleted;
- [ ] Identity verification in Intercom;
- [ ] Double opt-in for sign-up;
- [ ] Register & Login buttons placed on part-up closed page;
- [ ] Removed meurs strength finder (user profiles still contain already existing results);
- [ ] User can now see a restricted part-up when invited via email;
- [ ] Front-end now has an advanced tab on which
  - [ ] Users can delete their account;
  - [ ] Users can provide access rights to admins for impersonation;

**Comment by ralphboeije** [comment]
Testing on iOS and MacOS all relevant browsers

- [ ] A deleted activity title now shows with strikethrough;
- [ ] Single update & activity views now have the correct column span;
- [ ] Enable chat support via profile menu;
- [ ] Fixed floating login button;
- [ ] After accepting a tribe invite the go-to-tribe button changes;
- [ ] Update will still render if a user is deactivated/deleted;
- [ ] Identity verification in Intercom;
- [ ] Double opt-in for sign-up;
- [ ] Register & Login buttons placed on part-up closed page;
- [ ] Removed meurs strength finder (user profiles still contain already existing results);
- [ ] User can now see a restricted part-up when invited via email;
- [ ] Front-end now has an advanced tab on which
  - [ ] Users can delete their account;
  - [ ] Users can provide access rights to admins for impersonation;

**Comment by ralphboeije** [comment]
Issues found: 

- [ ] Firefox is extremely slow... Safari and Chrome have no issues with performance. Console shows these errors: Firefox can’t establish a connection to the server at wss://acceptance.part-up.com/websocket. Error: Cannot find module '/node_modules/meteor/socket-stream-client/sockjs-0.3.4.js'

<img width="1039" alt="screen shot 2018-06-13 at 08 27 01" src="https://user-images.githubusercontent.com/14044235/41333856-94879ed6-6ee3-11e8-9b98-1bc6c78d69c8.png">

- [ ] This error shows in FF after deleting a user profile

<img width="1321" alt="screen shot 2018-06-13 at 08 27 48" src="https://user-images.githubusercontent.com/14044235/41333883-b6039696-6ee3-11e8-8897-9978f7ae2d80.png">

- [ ] Must agree ToS keys still untranslated
- [ ] Impersonation in advance profile settings should only show after request by admin
- [ ] scrolling profile menu on iOS (Chrome and Safari) not functioning. When you scroll with the dropdown open, you move the background mainly instead of the dropdown.
- [ ] edge case, but nice to be covered: when you receive a link to a private part-up you now see the proper text and C2A buttons. However, when you are not invited, you still can't see the part-up after login in or signing up. So for logged in users, the text and the buttons should be different (i.e. go to tribe homepage button with corresponding text)
- [ ] In register flow: profile details is popping up twice
- [ ] Check needed on intercom id verify, as I can still see the intercom conversations of a user that just logged out
- [ ] Hidden Meurs profile still holds the space on the screen, which pushes the other profile data to the right column

**Comment by ralphboeije** [comment]
@noelheesen you have been fixing the wysiwyg, but now it does not show the text that has been edited before. You only see the placeholder text.
