### ISSUE TITLE
Tags not visible on profile on mobile browsers

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#219]
To reproduce:
- Visit a profile, e.g. https://part-up.com/profile/qvwyK2YX3gEmQYpPJ on a Safari on iOS 9
- see that only three out of 5 tags are shown

**Comment by andreleon** [comment]
I can see all the tags on the profile you provided

![simulator screen shot 04 apr 2016 08 49 04](https://cloud.githubusercontent.com/assets/1391492/14240073/23819952-fa42-11e5-96ab-debd72dd5df3.png)

**Comment by andreleon** [comment]
Only when the tags are very long they are capped off, still this is intended behaviour since it has the same behaviour on desktop
![simulator screen shot 04 apr 2016 08 53 56](https://cloud.githubusercontent.com/assets/1391492/14240153/ca906c8c-fa42-11e5-891e-6d212e1bdbe2.png)

![screen shot 2016-04-04 at 08 55 18](https://cloud.githubusercontent.com/assets/1391492/14240175/04103da2-fa43-11e5-97a2-a60c7897c64b.png)

**Comment by ralphboeije** [comment]
@andreleon fixed itself I guess....
