### ISSUE TITLE
Improve email templates

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#265]
Erik has created a redesign of the email templates: https://docs.google.com/document/d/1irEYc_ewkBf35f0QFeV1CneoTTltAeBOsTmNGOPpbq4/edit?usp=sharing

Still needs some work, but we really need to improve the design of the email templates in order to drive conversion and retention. #211 is needed first to be able to measure the impact.

**Comment by eriksoon** [comment]
The emails now have an unsubscribe that does not go to the mail settings page on Part-up. This way users can easily unsubscribe everything. It is better to let them choose which mails they don't want to receive, so guide them to https://part-up.com/profile/sgFxtsL7AoNRCDk7y/settings/email

**Comment by eriksoon** [comment]
I received an invite for Branded.me, which was sent out of the name of someone I know, and included her profile picture. I would like this for the invite of new uppers to the platform. It will increase the openrate and clickrate, because of social behavior. With Part-up at the moment, it is just text and the mail is sent by Part-up (so not the one taking the action to invite you).

Example:

![image](https://cloud.githubusercontent.com/assets/18055074/16132404/38c81330-3413-11e6-859d-e5e16a6ce71b.png)

**Comment by wouterd** [comment]
👍
