### ISSUE TITLE
Pricing page: one key is missing

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#286]
Really strange bug this is. On MacOS+chrome it shows: Up to 5 in this key: pages-app-pricing-tribe-starterskit-feature1-value

But on other browsers and on all browsers on win10 (incl chrome) the content of this key is not displayed (see screens).

Even stranger is that on one chrome browser on my MBP it shows the value of this key, but on the other (two users, two chrome browsers) it doesn't...
![schermafdruk 202016-03-08 2018 48 54](https://cloud.githubusercontent.com/assets/14044235/13614077/0e442f6a-e56f-11e5-8314-e80831d62452.png)

**Comment by andreleon** [comment]
@ralphboeije this is because the dutch translation is missing, either the key needs to be removed from the dutch translation file or the english translation has to be inserted in the dutch file.

![screen shot 2016-03-18 at 14 24 39](https://cloud.githubusercontent.com/assets/1391492/13878985/3ff0924e-ed15-11e5-8b63-0d64abff9511.png)

**Comment by ralphboeije** [comment]
@andreleon thanks, this was a side effect of the phraseapp refactor. I will just add the translations. Is there work to be done before this will work on the frontend after I add the translations to the keys?

**Comment by ralphboeije** [comment]
Laurens, here is the dutch copy. Can you check it? https://phraseapp.com/projects/part-up-webapp/locales/nl/translations?sorting=key_name_asc
