### ISSUE TITLE
Discuss Meteor 1.3 update and strategy to migrate

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#329]
```
=> Meteor 1.3 is available. Update this project with 'meteor update'.
```
- can we do this without breaking our stuffs?
- start using import for dep management
- try to test modules separately with import stuffs
- speed for writing tests en test the source is very important. Is the speed acceptable and does it need to build the whole meteor project again after changing the source code and test files?

**Comment by ralphboeije** [comment]
Saw stuffs on Cordova. As @jessedvrs will be working on the first native apps milestone, this might be impacting this sprint and/or be helpful or even needed in/for this sprint?

**Comment by ralphboeije** [comment]
Spoke to @jessedvrs today and he already did a deep dive into the migration and pro's and con's. He promised to share his findings here.

**Comment by AnnotatedJS** [comment]
@ralphboeije @jessedvrs Where can I find the findings of Jesse's deep dive?

**Comment by jessedvrs** [comment]
I started developing the [Part-up app](https://github.com/part-up/app) with Meteor 1.3.

__Full support of normal NPM and integrated Browserify__
We can use npm's package.json as we're used to (with `meteor npm` as the well-known `npm` CLI, since Meteor has a Node wrapper). And also for client-side use, since Browserify is integrated in Meteor 1.3.

__Improved ES6 support (ecmascript package)__
Finally get rid of the global namespace since we can use ES6's `import` calls. Meteor 1.3 doesn't eagerly (automatically) load files located in /imports. It's a good practice to move most of the files to the /imports directory. In an upcoming version of Meteor, they'll stop eagerly loading files by default. Since we're open-source and lots of pieces of code will be modularized (due to depricated global namespace), we can easily share code between server, web and app through npm.

__React-ready__
Meteor 1.3 is React-ready since Browserify is enabled by default and Meteor wrote a nice function to wrap React components with a Tracker (to provide Meteor data to React components as props). So we can safely start writing small pieces of the website in React (using JSX files). Though, this requires all users to download the entire React library (min + gzipped 26k). But once we fully replaced Blaze, we can remove Blaze from our dependency list.

__Migration__
As far as I know you can safely update to Meteor 1.3.1 without any problems.

__Cons__
No cons in comparison with Metoer 1.2.1!
