### ISSUE TITLE
Improve order of partner on new profile partners tab

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#340]
As an upper I want to show of my partners on my profile. So the new partners tab is great, but the ordering is not helpful to this end. It should be ordered by occurrence: number of times you are partner with this upper. And next on the upper score.

**Comment by andreleon** [comment]
I made some improvements on the sorting of partners in commit bdbdd3bb0bcd9d8f16ed958de2d6366293b7762b , the chunks(pages) of partners that are returned all have more frequent-partners than each following chunk, but the sorting of each chunk is still off. This is caused by the publication's inability to sort these chunks, this is a mongo/meteor bug.. (or something like that)

To completely fix this issue, I need a seperate array/object of partner_ids in the frontend that have been sorted by partner-frequency. That way I can sort them myself. That makes this a backend issue as well.

**Comment by ralphboeije** [comment]
Yes, thought of this as a backend issue at first, that's why I added the backend label.
