### ISSUE TITLE
image not showing in notification

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#460]
See screens. Just saw that an image was not showing in the notification. The strange thing is that it does show on hoover.

<img width="1440" alt="screen shot 2016-05-27 at 11 28 22" src="https://cloud.githubusercontent.com/assets/14044235/15604026/482b77e2-23fe-11e6-8fe9-665e5115834b.png">
<img width="1440" alt="screen shot 2016-05-27 at 11 28 24" src="https://cloud.githubusercontent.com/assets/14044235/15604028/484b0a30-23fe-11e6-9ab7-4116a876e911.png">

**Comment by ralphboeije** [comment]
@jessedvrs thought you fixed this in PR #396?

**Comment by jessedvrs** [comment]
Looks like some notification-types are missing in [this list](https://github.com/part-up/part-up/blob/develop/app/packages/partup:lib/collections/images.js#L53-L72). In PR #396 I only fixed the already listed notification-types, assuming all notification-types were listed. The fix is probably easy: just add the missing.
