### ISSUE TITLE
When logged in I want to first see the discoverpage iso home

### ISSUE THREAD

**Issue by eriksoon** [part-up/part-up#597]
When I open part-up and am already logged in, I'm still directed to the homepage (which doesn't add any value). I would like to be on the discover page since I now do not get confronted enough with new part-ups that might suite my profile/interest.

Windows, Chrome

![image](https://cloud.githubusercontent.com/assets/18055074/16867835/793a8624-4a74-11e6-9850-6c93689a7c69.png)

**Comment by ralphboeije** [comment]
We already have fixed this for new logins, but this is the case where the cookie is used to log in. So we need to enhance this feature.

**Comment by vanderGoes** [comment]
Is this issue still/back on the table for the big Q4 UX improvements?

**Comment by eriksoon** [comment]
I think it is valuable to have users landing on the discover page, since this is now a bit hidden.

**Comment by vanderGoes** [comment]
Can we turn it around? What are the arguments to keep the current home page as the landing page? Does @AriellevdLinde maybe know how often people scroll down? And what do they click?
(My) popular part-ups are all around 400 days old. Except one, which is 103 days old.

**Comment by AriellevdLinde** [comment]
I've checked a heatmap of the home page in VWO and only around 40% to 50% scrolls down to the popular part-ups section. The only thing is that I can't see how many users are logged in. 

Besides that I think it would be a good thing to land on another page then the homepage, because this page is nothing new for the user. Landing on the discover page would be a good start.
