### ISSUE TITLE
Prevent adding new duplicated part-ups in Meteor event hooks

### ISSUE THREAD

**Issue by tlimpanont** [part-up/part-up#628]

**Comment by tlimpanont** [comment]
@vanderGoes this happens after you create a new part-up right?

**Comment by vanderGoes** [comment]
Yes, not every time and only with new part-ups. As the node is new it cannot be locked yet.

Creating a part-up results in about 5 or 6 events (partups.inserted and multiple partups.updated). I guess because setting the end date, location etc reuses methods with those events included.

If we can reduce the events to one (partups.inserted) I expect that it won't be a problem. But we also need partups.updated later in the process.

**Comment by vanderGoes** [comment]
I added [constraints](https://neo4j.com/docs/developer-manual/current/cypher/#query-constraints) on `_id` for all nodes individually in Neo4j. Now a node can't be created if there is already another node with the same value for `_id`. Hope this fixes our duplication issue. I monitor it this week.

@tlimpanont you can pause your research on this issue for now. You're probably have enough other stuff to do :)

I'm also gonna check how this can be included every time a new Neo4j database is created. That can be used to add (search) indexes to the database. Which of course increases performance.

**Comment by wouterd** [comment]
What happens in the API when this constraint is not met?

**Comment by vanderGoes** [comment]
I expect that this error is logged and the query dropped:
`Node XXXX already exists with label Team and property "_id"=[XXXXXXXXXXXX]`
As a result maybe not all latest information is stored. But as the update-events send all entity data every time, this is corrected later on.

**Comment by wouterd** [comment]
If we can isolate that error code, we can just retry with an exponential back off (and a maximum retry amount) and stuff should settle down then.

**Comment by vanderGoes** [comment]
Good idea. Let's look into it on Tuesday? Also hope to know by then if it works. Now nobody starts part-ups :s
