### ISSUE TITLE
Add My tribes to global header

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#690]
Given I am a viewer of part-up.com
When I click the "Discover tribes" link
Then I am on the discover tribes page.

Given I am a logged in user
And I am not yet a member of a tribe
When I click the "Discover tribes" link
Then I am on the discover tribes page.

Given I am a logged in user of part-up.com
When I click the "My tribes" link
Then a dropdown opens showing the tribes I am member of
And I can see the "Discover more tribes" link

**Comment by AriellevdLinde** [comment]
@andreleon @ralphboeije 
The designs for My tribes is ready. If there are any question please let me know. 

**1.1 Logged in users that are already a member of a tribe will see "My tribes" in the header.**
![1 1 logged in - my tribes in header - topbar](https://cloud.githubusercontent.com/assets/22590642/19076925/e3348d34-8a4a-11e6-9129-769ab19bd820.png)

**1.2 User clicks "My tribes", a dropdown list will appear with a transparant background to have more focus:**
![1 2 logged in - my tribes in header - dropdown tribes](https://cloud.githubusercontent.com/assets/22590642/19076923/e3325258-8a4a-11e6-8847-a1adca9262e0.png)

**1.3 User hovers over one of the tribes, the list with my part-ups will appear**
![1 3 logged in - my tribes in header - dropdown part-ups in tribe](https://cloud.githubusercontent.com/assets/22590642/19076926/e337d638-8a4a-11e6-8187-86cd2f4ff0fd.png)

**1.4 User hovers over one of the part-ups in the specific tribe**
![1 4 logged in - my tribes in header - dropdown part-ups in tribe - select part-up](https://cloud.githubusercontent.com/assets/22590642/19076924/e3331f80-8a4a-11e6-930e-1cc5cf35ffdd.png)

**2. A Logged in user that isn't partner of any tribes yet, will see "discover tribes" instead of "my tribes" in the header **
![2 logged in - no tribe yet - topbar](https://cloud.githubusercontent.com/assets/22590642/19076927/e34bcc24-8a4a-11e6-9783-3975d2e93b46.png)

**3. A viewer will also see "discover tribes" instead of "my tribes" in the header**
![3 viewer - discover tribes - topbar](https://cloud.githubusercontent.com/assets/22590642/19076928/e35c1c1e-8a4a-11e6-8532-8a2086db649e.png)

**Comment by andreleon** [comment]
Since I don't have any visuals yet, I made a start. Don't worry, it can be changed ofcourse 😉

<img width="600" alt="screen shot 2016-10-04 at 16 50 00" src="https://cloud.githubusercontent.com/assets/1391492/19079072/9f993b94-8a52-11e6-8479-0a857bc6c3f2.png">

**Comment by andreleon** [comment]
Cool

**Comment by ralphboeije** [comment]
@AriellevdLinde what would you think of having all the dropdowns (my tribes, more, chat, notifications, user menu) in the global header activated on hoover instead of on-click as it is now?

**Comment by ralphboeije** [comment]
Looking good @andreleon !! @AriellevdLinde check http://feat-new-navigation.staging.part-up.com/ (login with user@example.com and pw user) to see the new navigation live.

My feedback for now:
- diagonal hoover is not working ok as you easily select the next tribe (what we discussed after the sprint planning). Did you already implement the 30 degrees angle tracking?
- Activity counter number overlaps part-up title when on two lines (e.g. "A semi-secret... part-up")
- I'm in doubt on the design of secondary navigation (will discuss it tomorrow with Arielle)

**Comment by andreleon** [comment]
@ralphboeije you are right about the 30 degrees tracking, I totally forgot about that (it's not mentioned in this issue 😉) so I will fix that today aswell as the activity counter

**Comment by AriellevdLinde** [comment]
Nice work @andreleon! I have some points of feedback:

- In the designs I've added a transparant layer (#292929, 10% transparency) that appears over the page when clicking on "my tribes". This to give the dropdown more attention. When closing the dropdown, the transparant layer will disappear. 

- When not logged in (and when not having any tribes yet), the user will see "discover tribes" instead of "my tribes". Until we actually have a "discover tribes" page, it should be "discover part-ups".

- The "my tribes" list and "my part-up" list will have a max. height. When there are more tribes/part-ups there will be a scroll bar (see 1.2.2 and 1.3.4). "Discover tribes" within the "my tribes" list will always be visible. The same for "view tribe". 

- The blue lines to show which tribe is selected are a little bit heavy. Therefor I've made them shorter (10px width). See the designs above for the new blue line.

- At the moment - when hovering a tribe - they grey rectangle isn't full width. This will only happen after a few seconds. Also the blue lines appear at that moment. It would be great if the grey hover rectangle will be immediately full width (on right side) and the blue lines will also appear. 

- I'm not sure about the animation when hovering a tribe, the part-up list appears that moment with a little fade in/slide in. How will it look like when we delete this animation? This way the part-ups can be seen faster because we don't have to show the animation every time you hover a tribe.

**Comment by ralphboeije** [comment]
Wow, looking good @andreleon!! Hoover action is now really fluid I think! @AriellevdLinde I don't think a scroll bar is really necessary, when we do not show the last tribe completely (so you know you have to scroll). What do you think?

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
The part-ups without a tribe and part-ups from tribes you aren't a member of will have there own secondary dropdown list, which will be shown at the bottom of the "my tribes" list and is called "Other part-ups". 

![1 2 logged in - my tribes in header - dropdown tribes all part-ups](https://cloud.githubusercontent.com/assets/22590642/19468369/378857aa-9516-11e6-95af-dc3ae69b1d88.png)

**Comment by AriellevdLinde** [comment]
@andreleon 
Other part-ups icon:
[Other part-ups icon.zip](https://github.com/part-up/part-up/files/535512/Other.part-ups.icon.zip)
