### ISSUE TITLE
Allow partners to invite each other to contribute to activities

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#692]
Given I am a partner in a part-up
And the part-ups has 1...n activities
And I am on the invite modal
And I searched and found a partner
And I see the invite button on this users upper tile
When I click Invite
Then a notification is send to this user to contribute to this activity
And an update is created "user x invited user Y to contribute to this activity" (same as non-partner invite to activity)

**Comment by AriellevdLinde** [comment]
@andreleon @ralphboeije 
When the person is already a partner in this part-up, instead of showing for example the location or "2 part-ups in common", show: "partner in this part-up" in green.  
![1 invite partners to activity - invite screen](https://cloud.githubusercontent.com/assets/22590642/19043679/7f9181e2-8991-11e6-8891-61af0365b7cd.png)

**Comment by ralphboeije** [comment]
@andreleon ready for development

**Comment by ralphboeije** [comment]
@andreleon check the design update for #696 as it is related to this issue.
