### ISSUE TITLE
Redesign in-part-up navigation

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#710]
To solve the following issues:
- Users can't see to which tribe the part-up belongs
  - Possible solution is a breadcrumb
- Users don't find the Activities tab (this assumption/feedback needs to be tested first in VWO)
  - Possible solution is to make the menu more visible
- Icons are hard to understand
  - Review icons

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
For the redesign of the in-part-up navigation I've made two versions, depending on how difficult it is to change it for development.

The changes that are the same in the two versions:
- The active menu item in the part-up navigation has a blue line instead of grey. This way it is easier to notice which one is active;
- The tribe the part-up belongs to can now be seen next to the part-up navigation (left or right, depending on the version);
- Documents is added to the design ( #720 );
- Social sharing can now be found next to the settings icon, instead of in the part-up information column. When clicking on it, the different types of sharing can be seen;
- Scrolling should be separate from each other. When scrolling the part-up information, the updates for example shouldn't scroll. When scrolling the updates, the part-up information shouldn't scroll. 

The two versions:

**"Ideal version"**
The "ideal version" has switched columns. Also, the part-up information column has a width of 400px instead of 523px. I would like to know how difficult it is to change this, because we are not sure yet if the user agrees with our ideal version. If it is a lot of work, I think we should first go for the "almost ideal version".

What also changed in this design is the order of part-up information and the presentation of it:
![v3 1 1 in-part-up navigation - overview - ideal version](https://cloud.githubusercontent.com/assets/22590642/19481734/3c878ed6-954f-11e6-8971-640d84cc31cf.png)

**"Almost ideal version"**
This version is exactly the same as the "ideal version", but then with the columns as it is at the moment. Also the part-up information column has the same width as it is at the moment (523px).
![v2 1 in-part-up navigation - overview - improved](https://cloud.githubusercontent.com/assets/22590642/19481914/c34e84e2-954f-11e6-829d-570b8b8b21ca.png)

**Besides the two versions, I've also designed the "social share" dropdown and how scrolling should look like. I've designed this for the "ideal version", but when we are going for the "almost ideal version" it will still be the same**:

**Hover social share**
![v3 1 2 in-part-up navigation - overview - ideal version - hover share](https://cloud.githubusercontent.com/assets/22590642/19482136/629174a6-9550-11e6-9210-5b8fd4be0ab4.png)

**Scroll right column (updates in this case)**
![v3 1 3 in-part-up navigation - overview - ideal version - scroll right](https://cloud.githubusercontent.com/assets/22590642/19482134/6268f652-9550-11e6-850b-f51da8eb4604.png)

**Scroll left column (part-up information in this case)**
![v3 1 4 in-part-up navigation - overview - ideal version - scroll left](https://cloud.githubusercontent.com/assets/22590642/19482135/626a052e-9550-11e6-9433-7227c5e608a7.png)

**Icons:**
[Icons_redesign in-part-up navigation.zip](https://github.com/part-up/part-up/files/536542/Icons_redesign.in-part-up.navigation.zip)

**Comment by ralphboeije** [comment]
Please have a look @LifelyPim

**Comment by ralphboeije** [comment]
@andreleon just saw this bug in safari. Probably fixed because of this redesign and redo of the scroll. 

<img width="1440" alt="screen shot 2016-11-07 at 15 45 14" src="https://cloud.githubusercontent.com/assets/14044235/20061718/50fa02f6-a501-11e6-8182-7a10173a1aea.png">

**Comment by ralphboeije** [comment]
@AriellevdLinde just noticed the access level is missing from the metadata in the part-up navigation redesign

**Comment by AriellevdLinde** [comment]
@ralphboeije @andreleon 
I've added the meta data "acces level" to the designs. You can find them in my previous post.

**Comment by AriellevdLinde** [comment]
@andreleon I just had a look at [staging](https://ft-partup-redesign.staging.part-up.com/partups/organise-a-meteor-meetup-vGaxNojSerdizDPjb) and it looks good! The only thing I notice is that some font(sizes) don't match with the design. Therefor I've made a Zeplin project, so you can see which font(sizes) I've used: https://zpl.io/Z20xfvm

**Comment by AriellevdLinde** [comment]
@andreleon 

Hereby I send you a checklist with some feedback:
- I noticed that the left column has the same width on every screen. Is it possible to always have the left column 25% and the right column 75% of the screen?
- Documents & links don't work at the moment
- Font sizes (but we already discussed this)
- Meta data "acces level" is missing (but that's because I delivered it yesterday)

**Comment by ralphboeije** [comment]
Documents & links work now. It was a database migration issue

**Comment by ralphboeije** [comment]
@andreleon just checked on https://ft-partup-responsive.staging.part-up.com/partups/partup-premium-part-up-WxrpPuJkhafJB3gfF and it looks like the right sidebar is still almost 30% of the screen width, instead of the 25% @AriellevdLinde requested.
