### ISSUE TITLE
High Prio: Since last release tribe of client not usable

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#773]
Tribe id: ewYYM9j3gvK34Rzoi 
NB: has same slug as another tribe somehow (with id: mb4xkSSt4eH63pDbp)

Findings: 
- Part-up in this tribe doesn't show the tribe anymore (see screenshot), id: wDM7zJiJJtu8qcRpn
- It is not possible to reach the tribe by the slug (maybe because of the other tribe)?
- Tribe admins can't see settings in the tribe
- About page content is gone in frontend (in database the content blocks still exist)

<img width="1440" alt="screen shot 2016-11-17 at 13 42 08" src="https://cloud.githubusercontent.com/assets/14044235/20389771/a6bcf712-accb-11e6-8d8c-3cd7240e1828.png">

**Comment by ralphboeije** [comment]
@peterpeerdeman any thoughts on this one?

**Comment by ralphboeije** [comment]
It seems an old version of this tribe is restored (but with a different tribe id?). Josje is admin in the other tribe with jso slug (with id: mb4xkSSt4eH63pDbp). She created the tribe at first and later handed it over to others (the admins in tribe with id ewYYM9j3gvK34Rzoi. Now there are two tribes with jso slug.

**Comment by peterpeerdeman** [comment]
I just looked into this issue. It looks like josje created a new tribe on 2016-11-15 (mb4xkSSt4eH63pDbp) with the same slug "jso" as the one created on 2016-10-19 (ewYYM9j3gvK34Rzoi). I changed the slug of the new duplicate tribe to "jso-temp" (https://part-up.com/tribes/jso-temp), the old tribe is visible now. the about contents are also preserved, but not visible to the public because it is a closed tribe.
