### ISSUE TITLE
Write migration for #907

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#916]
see #907

**Comment by prik** [comment]
Should be fixed now.

**Comment by prik** [comment]
Updated the migration. Please try again.

**Comment by peterpeerdeman** [comment]
@prik testcase for the partup with a board where the activities are missing is https://part-up.com/partups/community-management-Pj2dLoWtamQq58atR

**Comment by prik** [comment]
@ralphboeije @wouterd the reason that the activities are missing is because the migration hasn't run yet. I see that the table is locked and it's migrated to version 39, and 40 contains the fix. @wouterd can you unlock the migrations table and restart a server node? I ran it locally with the current dump and it showed no errors.

**Comment by wouterd** [comment]
Ah yes, it crashed out during the last migration. I'll fix it asap.

**Comment by wouterd** [comment]
I think it should work now. Can you check?

**Comment by prik** [comment]
Looks good to me :) @ralphboeije, can you check on your board(s)?

**Comment by ralphboeije** [comment]
Yes, it works now!!
