### ISSUE TITLE
Improve language detection

### ISSUE THREAD

**Issue by ralphboeije** [part-up/part-up#939]
Issues:
- when following an invite to an English part-up the language of the app is in dutch
- each time a user comes to part-up.com (automatic cookie login) the language of the platform goes back to dutch and has to be switched it back manually to English

Some history:
- First we used browser based language setting. This was an issue for several Dutch users, as their organizations' IT department put the browser language on English. Users could change it in their profile settings, but this is inconvenient for users
- Then we used IP based language setting, using a Google API, but that didn't work right, so now it defaults back to Dutch always
- Then we introduced the manual language setting on the homepage and we introduced the language override for not logged in users on tribes that have EN as language setting.

Also related to #840

**Comment by ralphboeije** [comment]
Finding by @wouterd 

Easily reproduced by F5-ing. 90% sure this has to do with the work done in a recent release with detecting the tribe language and setting it accordingly for non-logged in users. Race condition where two branches of init code have a battle who wins.

**Comment by andreleon** [comment]
In commit 8b2728368626032e6ceca22d1122b1d45acbf800 the language detection/changing is refactored.

This is now the language service works:

If the user is **not** logged in:

1. Partup will detect the browser language
2. Partup will set the language to the given browser language
3. if the language is anything other than Dutch, Partup will default to English

If the user is logged in:

1. Partup will fetch the language from the logged in user's profile
2. Partup will set the language to the given language
3. If no language is set by the user, Partup will detect the browser language
4. Partup will set the language to the given browser language
5. if the language is anything other than Dutch, Partup will default to English

There is only one service that detects the language and changes the partup UI on any given moment so no conflicts arise anymore. So Networks and Partups with different languages will not affect the UI of Partup anymore, since this is not nessecary. The UI language is always set based on the current user's preference, wether it's the profile setting or browser default, we can always asume the user is able to understand/use partup based on their environment or preference.

The language CAN be set in more than one location however.
- Profile Settings
- Home (logged out state)

**Comment by ralphboeije** [comment]
Just tested it and it works like a charm! Thanks @andreleon
