### ISSUE TITLE
Improve :focus states and ARIA-Labels and Service Worker for Offline pages

### ISSUE THREAD

**Issue by camille500** [part-up/part-up#982]
- [ ] Better focus and active states
- [ ] Optimized for screenreaders (ARIA-Labels)
- [ ] Service Worker so that the site can be viewed offline

**Comment by camille500** [comment]
Other project

**Comment by Murderlon** [comment]
Try to make separate issues for every problem. Also check whether it already exits, if it does and it's unassigned, you can just work on that and refer to that issue in your PR.

These are currently duplicates:
"Better focus and active states" --> #983
"Service Worker so that the site can be viewed offline" --> #980

**Comment by ralphboeije** [comment]
Hi @camille500  great that you'll be working on these issue. As product owner, I am here to answer any question you might have. I agree that one problem per issue is the best way to move forward.

**Comment by camille500** [comment]
Thanks for the feedback @Murderlon!  I'll make seperate issues!
@ralphboeije thanks, if I have questions I will let you know!
